### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by jtmoulia** [jeremyong/websocket_client#40]
The last release was around a year ago, and I'd love to be using a tagged release with the more recent extra headers patch.

**Comment by jeremyong** [comment]
Hi there! I'm not actively writing Erlang code at the moment but if you'd like to contribute a patch, I'd be happy to review it and accept it.

**Comment by jtmoulia** [comment]
Hey, the commit I'm eying is already in master: https://github.com/jeremyong/websocket_client/commit/652f24c2db3c2292194131690e481770d5375fb5. Tagging a release would just be useful for managing deps.

**Comment by jeremyong** [comment]
Done!

**Comment by jtmoulia** [comment]
Thanks!!!
